/*
2021-11-12
https://www.researchgate.net/publication/323787227_Openlobby_an_open_game_server_for_lobby_and_matchmaking
DATABASE: OPEN_LOBBY 
TABLES
    GAME, PLAYER, GAME_SESSION, MATCHING_QUEUE
*/

CREATE TABLE GAME
(
    GAME_ID INT(10) NOT NULL AUTO_INCREMENT,
    GAME_NAME VARCHAR(20) NOT NULL,
    DEVELOPER_NAME VARCHAR(30) NOT NULL,
    PROPERTIES VARCHAR(30),
    SERVICE_START_DATE DATE,
    SERVICE_STATUS INT NOT NULL,
    MATCHMAKING_ALGORITHM INT NOT NULL,
    SESSION_EXPIRY INT NOT NULL,
    PRIMARY KEY (GAME_ID)
);

CREATE TABLE PLAYER
(
    PLAYER_ID INT(10) NOT NULL,
    USER_NAME VARCHAR(30) NOT NULL,
    GAME_ID INT(10) NOT NULL,
    EXPERIENCE VARCHAR(30),
    PROPERTIES VARCHAR(30),
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID) ON UPDATE CASCADE
);

CREATE TABLE GAME_SESSION
(
    SESSION_ID INT(10) NOT NULL AUTO_INCREMENT,
    SESSION_STATUS INT(10) NOT NULL,
    SESSION_SUCCESS INT(10),
    SESSION_HOST_ID INT(10),
    PRIMARY KEY(SESSION_ID)
);

CREATE TABLE MATCHING_QUEUE
(
    QUEUE_ID INT(10) NOT NULL AUTO_INCREMENT,
    PLAYER_ID INT(10) NOT NULL,
    PLAYER_IP VARCHAR(20),
    TIME_QUEUE DATE,
    QUEUE_STATUS INT(10) NOT NULL,
    SESSION_ID INT(10),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID) ON UPDATE CASCADE,
    FOREIGN KEY (SESSION_ID) REFERENCES GAME_SESSION(SESSION_ID) ON UPDATE CASCADE,
    PRIMARY KEY (QUEUE_ID)
);

